"""
Adds the finance glossary (20 terms) to finance_real.db.

The WRDS pull script (wrds_pull_and_load.py) creates the `glossary` table
via schema.sql but doesn't populate it — this fills it in, so
finance_real.db has the same "display finance knowledge" table the
synthetic finance.db has.

Usage:
    python populate_glossary.py
"""
import sqlite3

DB_PATH = "finance_real.db"

GLOSSARY = [
    ("Gross Margin", "Profitability", "The percentage of revenue remaining after subtracting cost of goods sold (COGS). Measures production/service efficiency before overhead.", "Gross Profit / Revenue"),
    ("Operating Margin", "Profitability", "The percentage of revenue left after subtracting both COGS and operating expenses, before interest and tax.", "Operating Income / Revenue"),
    ("Net Margin", "Profitability", "The percentage of revenue that converts into net profit after all expenses, interest and tax.", "Net Income / Revenue"),
    ("Return on Equity (ROE)", "Profitability", "How efficiently a company generates profit from shareholders' equity.", "Net Income / Total Equity"),
    ("Return on Assets (ROA)", "Profitability", "How efficiently a company uses its total assets to generate profit.", "Net Income / Total Assets"),
    ("Current Ratio", "Liquidity", "Measures a company's ability to pay short-term obligations with short-term assets. Above 1.0 generally indicates adequate liquidity.", "Current Assets / Current Liabilities"),
    ("Quick Ratio", "Liquidity", "A stricter liquidity measure that excludes inventory, since inventory is not always quickly convertible to cash.", "(Current Assets - Inventory) / Current Liabilities"),
    ("Debt-to-Equity Ratio", "Solvency", "Compares total liabilities to shareholder equity, indicating how much of the business is financed by debt versus owners' capital.", "Total Liabilities / Total Equity"),
    ("Free Cash Flow (FCF)", "Cash Flow", "Cash generated by operations after subtracting capital expenditures — cash available for dividends, buybacks, debt repayment or reinvestment.", "Operating Cash Flow - Capital Expenditures"),
    ("EPS (Earnings Per Share)", "Valuation", "The portion of a company's net income allocated to each outstanding share of common stock.", "Net Income / Shares Outstanding"),
    ("P/E Ratio", "Valuation", "Price-to-earnings ratio: how much investors are willing to pay per pound/dollar of earnings. A high P/E can indicate growth expectations or overvaluation.", "Share Price / EPS"),
    ("Market Capitalization", "Valuation", "The total market value of a company's outstanding shares.", "Share Price × Shares Outstanding"),
    ("Working Capital", "Liquidity", "The capital available for day-to-day operations, representing short-term financial health.", "Current Assets - Current Liabilities"),
    ("CAGR (Compound Annual Growth Rate)", "Growth", "The mean annual growth rate of a value over a specified period, assuming compounding.", "(End Value / Start Value)^(1/Years) - 1"),
    ("EBITDA", "Profitability", "Earnings before interest, tax, depreciation and amortization — a proxy for operating cash-generating ability that strips out financing and accounting decisions.", "Operating Income + Depreciation + Amortization"),
    ("Volatility (Std Dev of Returns)", "Market", "A statistical measure of the dispersion of returns, commonly used as a proxy for investment risk.", "Standard Deviation of Daily Returns"),
    ("Dividend Yield", "Valuation", "Annual dividends paid per share relative to the share price, expressed as a percentage.", "Annual Dividend Per Share / Share Price"),
    ("Beta", "Market", "A measure of a stock's volatility relative to the overall market. Beta > 1 implies more volatile than the market.", "Covariance(Stock, Market) / Variance(Market)"),
    ("Inventory Turnover", "Efficiency", "How many times a company sells and replaces its inventory over a period — higher generally indicates stronger sales or lean inventory management.", "COGS / Average Inventory"),
    ("Interest Coverage Ratio", "Solvency", "Measures how easily a company can pay interest on outstanding debt from its operating income.", "Operating Income / Interest Expense"),
]


def main():
    conn = sqlite3.connect(DB_PATH)
    existing = conn.execute("SELECT COUNT(*) FROM glossary").fetchone()[0]
    if existing > 0:
        print(f"glossary already has {existing} rows — skipping insert (nothing to do).")
        conn.close()
        return

    rows = [(i + 1, term, cat, definition, formula) for i, (term, cat, definition, formula) in enumerate(GLOSSARY)]
    conn.executemany(
        "INSERT INTO glossary (term_id, term, category, definition, formula) VALUES (?,?,?,?,?)",
        rows,
    )
    conn.commit()
    n = conn.execute("SELECT COUNT(*) FROM glossary").fetchone()[0]
    print(f"Inserted {n} glossary terms into {DB_PATH}")
    conn.close()


if __name__ == "__main__":
    main()
